--
-- PostgreSQL database cluster dump
--

\restrict S5d4HNN9Z6C0dDVBKbxnusXcPBSh3nLqriH5DhsioUlKWpxbYiVT0IIbkeRoV0s

SET default_transaction_read_only = off;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

--
-- Roles
--

CREATE ROLE postgres;
ALTER ROLE postgres WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:liemsnQH605cZQSnVHkHLg==$oY+NU1yZhkmmynQB3hs/lFg5rqViMsxPmb4YjFjpSic=:VBRQ7Pv+B+Vmsx62xN/sRCv7pJnyP989ctFsA5zzFCc=';

--
-- User Configurations
--








\unrestrict S5d4HNN9Z6C0dDVBKbxnusXcPBSh3nLqriH5DhsioUlKWpxbYiVT0IIbkeRoV0s

--
-- Databases
--

--
-- Database "template1" dump
--

\connect template1

--
-- PostgreSQL database dump
--

\restrict bJZV8FI6budq4mI3eh3ZdjaiXgGEeVjLaHsPqMjk6JPNgfIbqm10ESf36DhUHck

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- PostgreSQL database dump complete
--

\unrestrict bJZV8FI6budq4mI3eh3ZdjaiXgGEeVjLaHsPqMjk6JPNgfIbqm10ESf36DhUHck

--
-- Database "lankaassist_assistance" dump
--

--
-- PostgreSQL database dump
--

\restrict qnz0J9MSsO3Pe9qmT3CICN7COnDBEcLTJKAsCTGJbs6fN9XRXPagWKrNX3Cn7JW

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: lankaassist_assistance; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE lankaassist_assistance WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';


ALTER DATABASE lankaassist_assistance OWNER TO postgres;

\unrestrict qnz0J9MSsO3Pe9qmT3CICN7COnDBEcLTJKAsCTGJbs6fN9XRXPagWKrNX3Cn7JW
\connect lankaassist_assistance
\restrict qnz0J9MSsO3Pe9qmT3CICN7COnDBEcLTJKAsCTGJbs6fN9XRXPagWKrNX3Cn7JW

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: assistance_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.assistance_requests (
    id bigint NOT NULL,
    assistance_type character varying(30) NOT NULL,
    beneficiary_type character varying(20) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    crisis_type character varying(30) NOT NULL,
    description character varying(1000) NOT NULL,
    district character varying(50) NOT NULL,
    requested_amount numeric(12,2),
    requester_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    title character varying(120) NOT NULL,
    CONSTRAINT assistance_requests_assistance_type_check CHECK (((assistance_type)::text = ANY ((ARRAY['MONEY'::character varying, 'FOOD'::character varying, 'MEDICAL'::character varying, 'SHELTER'::character varying, 'EDUCATION'::character varying, 'PHYSICAL_HELP'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT assistance_requests_beneficiary_type_check CHECK (((beneficiary_type)::text = ANY ((ARRAY['INDIVIDUAL'::character varying, 'GROUP'::character varying])::text[]))),
    CONSTRAINT assistance_requests_crisis_type_check CHECK (((crisis_type)::text = ANY ((ARRAY['FINANCIAL_CRISIS'::character varying, 'NATURAL_DISASTER'::character varying])::text[]))),
    CONSTRAINT assistance_requests_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.assistance_requests OWNER TO postgres;

--
-- Name: assistance_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.assistance_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assistance_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: assistance_requests; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.assistance_requests (id, assistance_type, beneficiary_type, created_at, crisis_type, description, district, requested_amount, requester_id, status, title) FROM stdin;
1	MONEY	INDIVIDUAL	2026-09-12 10:21:23.094636	FINANCIAL_CRISIS	Financial assistance required for educational expenses	Colombo	25000.00	2	PENDING	University educational support
\.


--
-- Name: assistance_requests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.assistance_requests_id_seq', 1, true);


--
-- Name: assistance_requests assistance_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assistance_requests
    ADD CONSTRAINT assistance_requests_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict qnz0J9MSsO3Pe9qmT3CICN7COnDBEcLTJKAsCTGJbs6fN9XRXPagWKrNX3Cn7JW

--
-- Database "lankaassist_contribution" dump
--

--
-- PostgreSQL database dump
--

\restrict ZjR9zea2lWlM4D6y7L15gClDua3cfVSbcVqIh6YrasTAIKOOcy7xnfMTLUTRhRh

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: lankaassist_contribution; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE lankaassist_contribution WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';


ALTER DATABASE lankaassist_contribution OWNER TO postgres;

\unrestrict ZjR9zea2lWlM4D6y7L15gClDua3cfVSbcVqIh6YrasTAIKOOcy7xnfMTLUTRhRh
\connect lankaassist_contribution
\restrict ZjR9zea2lWlM4D6y7L15gClDua3cfVSbcVqIh6YrasTAIKOOcy7xnfMTLUTRhRh

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: contributions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contributions (
    id bigint NOT NULL,
    amount numeric(12,2),
    anonymous_donor boolean NOT NULL,
    assistance_request_id bigint NOT NULL,
    contribution_type character varying(30) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(500) NOT NULL,
    donor_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    CONSTRAINT contributions_contribution_type_check CHECK (((contribution_type)::text = ANY ((ARRAY['MONEY'::character varying, 'GOODS'::character varying, 'PHYSICAL_HELP'::character varying])::text[]))),
    CONSTRAINT contributions_status_check CHECK (((status)::text = ANY ((ARRAY['PLEDGED'::character varying, 'VERIFIED'::character varying, 'ALLOCATED'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.contributions OWNER TO postgres;

--
-- Name: contributions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contributions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contributions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: contributions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.contributions (id, amount, anonymous_donor, assistance_request_id, contribution_type, created_at, description, donor_id, status) FROM stdin;
1	9999.91	t	1	MONEY	2026-09-12 10:36:21.94125	Contribution for university educational support	3	PLEDGED
\.


--
-- Name: contributions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.contributions_id_seq', 1, true);


--
-- Name: contributions contributions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contributions
    ADD CONSTRAINT contributions_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict ZjR9zea2lWlM4D6y7L15gClDua3cfVSbcVqIh6YrasTAIKOOcy7xnfMTLUTRhRh

--
-- Database "lankaassist_coordination" dump
--

--
-- PostgreSQL database dump
--

\restrict wva1IkDNfkUvub82uyxWcueFqBe7FOimSqZxMCdcdYCE0rpqkJzkDPK7oma7KZc

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: lankaassist_coordination; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE lankaassist_coordination WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';


ALTER DATABASE lankaassist_coordination OWNER TO postgres;

\unrestrict wva1IkDNfkUvub82uyxWcueFqBe7FOimSqZxMCdcdYCE0rpqkJzkDPK7oma7KZc
\connect lankaassist_coordination
\restrict wva1IkDNfkUvub82uyxWcueFqBe7FOimSqZxMCdcdYCE0rpqkJzkDPK7oma7KZc

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: resource_allocations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.resource_allocations (
    id bigint NOT NULL,
    assistance_request_id bigint NOT NULL,
    contribution_id bigint NOT NULL,
    coordinator_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    notes character varying(500),
    status character varying(20) NOT NULL,
    CONSTRAINT resource_allocations_status_check CHECK (((status)::text = ANY ((ARRAY['ASSIGNED'::character varying, 'IN_PROGRESS'::character varying, 'DELIVERED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.resource_allocations OWNER TO postgres;

--
-- Name: resource_allocations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.resource_allocations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resource_allocations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: resource_allocations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.resource_allocations (id, assistance_request_id, contribution_id, coordinator_id, created_at, notes, status) FROM stdin;
1	1	1	6	2026-09-12 12:01:28.224836	Initial allocation for university educational support	IN_PROGRESS
\.


--
-- Name: resource_allocations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.resource_allocations_id_seq', 1, true);


--
-- Name: resource_allocations resource_allocations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.resource_allocations
    ADD CONSTRAINT resource_allocations_pkey PRIMARY KEY (id);


--
-- Name: resource_allocations uk_allocation_contribution; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.resource_allocations
    ADD CONSTRAINT uk_allocation_contribution UNIQUE (contribution_id);


--
-- PostgreSQL database dump complete
--

\unrestrict wva1IkDNfkUvub82uyxWcueFqBe7FOimSqZxMCdcdYCE0rpqkJzkDPK7oma7KZc

--
-- Database "lankaassist_identity" dump
--

--
-- PostgreSQL database dump
--

\restrict oGW8YrMzKyAWFHRAj2BJFygsdJKz8ch3z3uqXeuREKR0Lw5654IIAqIYaFrMeax

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: lankaassist_identity; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE lankaassist_identity WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';


ALTER DATABASE lankaassist_identity OWNER TO postgres;

\unrestrict oGW8YrMzKyAWFHRAj2BJFygsdJKz8ch3z3uqXeuREKR0Lw5654IIAqIYaFrMeax
\connect lankaassist_identity
\restrict oGW8YrMzKyAWFHRAj2BJFygsdJKz8ch3z3uqXeuREKR0Lw5654IIAqIYaFrMeax

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    anonymous_donor boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(150) NOT NULL,
    full_name character varying(100) NOT NULL,
    password_hash character varying(255) NOT NULL,
    role character varying(20) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['APPLICANT'::character varying, 'DONOR'::character varying, 'VOLUNTEER'::character varying, 'ADMIN'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, anonymous_donor, created_at, email, full_name, password_hash, role) FROM stdin;
1	f	2026-09-11 18:22:18.741368	kamal@example.com	Kamal Silva	$2a$10$VmMg8aGWxOLyYYagfWS2KeXzZj9RtVcBNKfXWLrwdMUMSV05uycu2	APPLICANT
2	f	2026-09-12 01:41:07.441204	kamal2@example.com	Kamal Perera	$2a$10$HlfeY08KXmK70u0VJXO6wuUSuGGpXMqxKdTfsvpskKSh9TB0ejHsS	APPLICANT
3	t	2026-09-12 10:33:16.364512	nimal.donor2026@example.com	Nimal Donor	$2a$10$hB.II99vc2Ms0tndVXVvtOUwTJYPa/z6eTkqI7dhdnlJcSlw9KNFO	DONOR
4	f	2026-09-12 11:18:31.506572	saman.volunteer2026@example.com	Saman Volunteer	$2a$10$DGWZn3DlLOo7/VgrUbg7uuO5Z1MIWUOxTUpsyZ8xYtcgOrUq.KqRi	VOLUNTEER
5	f	2026-09-12 11:21:31.864182	kasun.volunteer2026@example.com	kasun volunteer	$2a$10$DonGZ3TlXLt7WHHED1soiey.p2UDUAGIUWNpKRfT0IpPo5HYweQWS	VOLUNTEER
6	f	2026-09-12 11:25:23.31035	admin2026@lankaassist.local	LankaAssist Administrator	$2a$10$EDBDXm4r4rQ90uO7AkJicODXdvzRYkc1tYzHbGQ/ganN3NQ.nF0rS	ADMIN
7	t	2026-09-12 12:13:11.184384	chinthaka@123.gmail	Chinthaka	$2a$10$s/0ZygYf4rQKVwtbDTlCLu8KgujvSMaPvUssYwDjaPvXhTx6FW9nO	DONOR
\.


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 7, true);


--
-- Name: users uk_users_email; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_users_email UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict oGW8YrMzKyAWFHRAj2BJFygsdJKz8ch3z3uqXeuREKR0Lw5654IIAqIYaFrMeax

--
-- Database "postgres" dump
--

\connect postgres

--
-- PostgreSQL database dump
--

\restrict llcgZeuQpBYP3kQB09yJChBikUJW7JDZbe9cqddUjZg5aYZKxUTVZUd7TCJBGA9

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- PostgreSQL database dump complete
--

\unrestrict llcgZeuQpBYP3kQB09yJChBikUJW7JDZbe9cqddUjZg5aYZKxUTVZUd7TCJBGA9

--
-- PostgreSQL database cluster dump complete
--

