server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: identity-service
              uri: "${IDENTITY_SERVICE_URI:http://identity-service:8081}"
              predicates:
                - Path=/api/auth/**

            - id: assistance-service
              uri: "${ASSISTANCE_SERVICE_URI:http://assistance-service:8086}"
              predicates:
                - Path=/api/assistance/**

            - id: contribution-service
              uri: "${CONTRIBUTION_SERVICE_URI:http://contribution-service:8083}"
              predicates:
                - Path=/api/contributions/**

            - id: coordination-service
              uri: "${COORDINATION_SERVICE_URI:http://coordination-service:8084}"
              predicates:
                - Path=/api/allocations/**
management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always
      